index:
    path: /
    controller: App\Controller\HolmesPlaceController::Index

home:
    path: /index
    controller: App\Controller\HolmesPlaceController::Index

login:
    path: /login
    controller: App\Controller\SecurityController::login
    
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout   
    
holmesplace:
    path: /admin
    controller: App\Controller\HolmesPlaceController::Admin

holmesplace_summary:
    path: /summary
    controller: App\Controller\HolmesPlaceController::SummaryPage    

weather:
    path: /weather/update
    controller: App\Controller\HolmesPlaceController::UpdateWeather

weather_main:
    path: /weather
    controller: App\Controller\HolmesPlaceController::Weather

bee:
    path: /bees/{page}
    controller: App\Controller\HolmesPlaceController::BeeApp
     
crypto:
    path: /crypto/
    controller: App\Controller\CryptoController::c_index

crypto_transactions_query:
    path: /crypto/transactions/query
    controller: App\Controller\CryptoController::queryTransactions
    
crypto_transactions:
    path: /crypto/transactions/show
    controller: App\Controller\CryptoController::showTransactions
  
crypto_wallets:
    path: /crypto/wallets
    controller: App\Controller\CryptoController::showWallets
    
crypto_showticker:
   path: /crypto/showticker/{pair}
   controller: App\Controller\CryptoController::showTickerData

crypto_update:
   path: /crypto/update
   controller: App\Controller\CryptoController::updateCryptoPrices
   
crypto_readin:
   path: /readin
   controller: App\Controller\CryptoController::readInTransactions
      
vehicle:
    path: /vehicle
    controller: App\Controller\VehicleController::v_index
    
vehicle_fuel:
    path: vehicle/fuel
    controller: App\Controller\VehicleController::FuelEntry   
 
vehicle_trip:
    path: vehicle/trip
    controller: App\Controller\VehicleController::TripEntry
  
task_success:
    path:   /task_success/{slug}
    defaults:
        slug: 'Default'
    controller: App\Controller\HolmesPlaceController::task_success


