index:
    path:   /
    controller: App\Controller\HolmesPlaceController::index
    
fuel:
    path:   /fuel
    controller: App\Controller\HolmesPlaceController::FuelEntry

server:
    path:   /server
    controller: App\Controller\HolmesPlaceController::NewServer
