index:
    path:   /
    controller: App\Controller\HolmesPlaceController::Index

login:
    path: /login
    controller: App\Controller\SecurityController::login
    
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout   
holmesplace:
    path: /admin
    controller: App\Controller\HolmesPlaceController::Admin
trip:
    path:   /trip
    controller: App\Controller\HolmesPlaceController::TripEntry
crypto:
    path: /crypto
    controller: App\Controller\HolmesPlaceController::CryptoEntry
    
crypto_showticker:
   path: /crypto/showticker
   controller: App\Controller\HolmesPlaceController::showTickerData

crypto_update:
   path: /crypto/update
   controller: App\Controller\HolmesPlaceController::updateCryptoPrices
      
summary:
    path:   /summary
    controller: App\Controller\HolmesPlaceController::SummaryPage    

fuel:
    path:   /fuel
    controller: App\Controller\HolmesPlaceController::FuelEntry
    
readin:
    path: /readin
    controller: App\Controller\HolmesPlaceController::DisplayTransactions
    
task_success:
    path:   /task_success/{slug}
    defaults:
        slug: 'Default'
    controller: App\Controller\HolmesPlaceController::task_success


